# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'housePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 558)
        self.page = QtWidgets.QWidget()
        self.page.setMinimumSize(QtCore.QSize(768, 432))
        self.page.setMaximumSize(QtCore.QSize(1536, 864))
        self.page.setObjectName("page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sideBar = QtWidgets.QWidget(self.page)
        self.sideBar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sideBar.sizePolicy().hasHeightForWidth())
        self.sideBar.setSizePolicy(sizePolicy)
        self.sideBar.setMinimumSize(QtCore.QSize(153, 0))
        self.sideBar.setMaximumSize(QtCore.QSize(308, 16777215))
        self.sideBar.setStyleSheet("")
        self.sideBar.setObjectName("sideBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sideBar)
        self.verticalLayout.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.houseInfo = QtWidgets.QFrame(self.sideBar)
        self.houseInfo.setMinimumSize(QtCore.QSize(0, 330))
        self.houseInfo.setMaximumSize(QtCore.QSize(16777215, 500))
        self.houseInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.houseInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.houseInfo.setObjectName("houseInfo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.houseInfo)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.houseTitle = QtWidgets.QFrame(self.houseInfo)
        self.houseTitle.setMinimumSize(QtCore.QSize(0, 72))
        self.houseTitle.setMaximumSize(QtCore.QSize(16777215, 72))
        self.houseTitle.setObjectName("houseTitle")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.houseTitle)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.backButton = QCutomButton(self.houseTitle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        self.backButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.backButton.setStyleSheet("background-color: transparent; border-style: none;")
        self.backButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/chevron-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_4.addWidget(self.backButton)
        self.houseName = QtWidgets.QPushButton(self.houseTitle)
        self.houseName.setMinimumSize(QtCore.QSize(60, 15))
        self.houseName.setMaximumSize(QtCore.QSize(100, 25))
        self.houseName.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.houseName.setObjectName("houseName")
        self.horizontalLayout_4.addWidget(self.houseName)
        self.verticalLayout_4.addWidget(self.houseTitle)
        self.numRoom = QtWidgets.QFrame(self.houseInfo)
        self.numRoom.setMinimumSize(QtCore.QSize(0, 72))
        self.numRoom.setMaximumSize(QtCore.QSize(16777215, 72))
        self.numRoom.setObjectName("numRoom")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.numRoom)
        self.horizontalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_9 = QtWidgets.QWidget(self.numRoom)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 72))
        self.widget_9.setMaximumSize(QtCore.QSize(16777215, 72))
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-familiy: \'poppins\';")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget_9)
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_5.addWidget(self.widget_9)
        self.plusButton = QtWidgets.QPushButton(self.numRoom)
        self.plusButton.setMinimumSize(QtCore.QSize(52, 52))
        self.plusButton.setMaximumSize(QtCore.QSize(52, 52))
        self.plusButton.setObjectName("plusButton")
        self.horizontalLayout_5.addWidget(self.plusButton)
        self.verticalLayout_4.addWidget(self.numRoom)
        self.capacity = QtWidgets.QFrame(self.houseInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capacity.sizePolicy().hasHeightForWidth())
        self.capacity.setSizePolicy(sizePolicy)
        self.capacity.setMinimumSize(QtCore.QSize(0, 72))
        self.capacity.setMaximumSize(QtCore.QSize(16777215, 72))
        self.capacity.setObjectName("capacity")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.capacity)
        self.horizontalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_11 = QtWidgets.QWidget(self.capacity)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 72))
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget_11)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget_11)
        self.label_7.setMinimumSize(QtCore.QSize(0, 10))
        self.label_7.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_7.addWidget(self.widget_11)
        self.editButton = QtWidgets.QPushButton(self.capacity)
        self.editButton.setMinimumSize(QtCore.QSize(52, 52))
        self.editButton.setMaximumSize(QtCore.QSize(52, 52))
        self.editButton.setObjectName("editButton")
        self.horizontalLayout_7.addWidget(self.editButton)
        self.verticalLayout_4.addWidget(self.capacity)
        self.consum = QtWidgets.QFrame(self.houseInfo)
        self.consum.setMinimumSize(QtCore.QSize(0, 72))
        self.consum.setMaximumSize(QtCore.QSize(16777215, 72))
        self.consum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.consum.setFrameShadow(QtWidgets.QFrame.Raised)
        self.consum.setObjectName("consum")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.consum)
        self.verticalLayout_6.setContentsMargins(12, 3, 12, 3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.consum)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.consum)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.verticalLayout_4.addWidget(self.consum)
        self.verticalLayout.addWidget(self.houseInfo)
        spacerItem = QtWidgets.QSpacerItem(20, 90, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.runButton = QtWidgets.QFrame(self.sideBar)
        self.runButton.setMinimumSize(QtCore.QSize(0, 70))
        self.runButton.setMaximumSize(QtCore.QSize(16777215, 80))
        self.runButton.setObjectName("runButton")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.runButton)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.runButton)
        self.pushButton_3.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_7.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.runButton)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.sideBar)
        self.roomSpace = QtWidgets.QWidget(self.page)
        self.roomSpace.setEnabled(False)
        self.roomSpace.setMinimumSize(QtCore.QSize(461, 432))
        self.roomSpace.setStyleSheet("background-color: \"#D9D9D9\";\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;")
        self.roomSpace.setObjectName("roomSpace")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.roomSpace)
        self.horizontalLayout_3.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.roomSpace)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 432))
        self.scrollArea_2.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: \'#d9d9d9\';\n"
"    width: 12px;\n"
"    margin: 20px 0 20px 0;\n"
"    border-radius: 5px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: \'#a1a1a1\';\n"
"    min-height: 30px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: \'#696969\';\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: 15px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"")
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 260, 1518))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget.setMinimumSize(QtCore.QSize(0, 1500))
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.addWidget(self.scrollArea_2)
        self.detailRoomSpace = QtWidgets.QFrame(self.roomSpace)
        self.detailRoomSpace.setMaximumSize(QtCore.QSize(308, 16777215))
        self.detailRoomSpace.setStyleSheet("background-color: \"#98ABC8\";\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;")
        self.detailRoomSpace.setObjectName("detailRoomSpace")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.detailRoomSpace)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.detailRoom = QtWidgets.QWidget(self.detailRoomSpace)
        self.detailRoom.setObjectName("detailRoom")
        self.verticalLayout_3.addWidget(self.detailRoom)
        self.horizontalLayout_3.addWidget(self.detailRoomSpace)
        self.horizontalLayout.addWidget(self.roomSpace)
        MainWindow.addWidget(self.page)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "StackedWidget"))
        self.houseName.setText(_translate("MainWindow", "Rumah Angker"))
        self.label_2.setText(_translate("MainWindow", "Jumlah Ruangan"))
        self.label.setText(_translate("MainWindow", "5"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.label_6.setText(_translate("MainWindow", "Kapasitas"))
        self.label_7.setText(_translate("MainWindow", "1100 Watt"))
        self.editButton.setText(_translate("MainWindow", "edit"))
        self.label_8.setText(_translate("MainWindow", "Konsumsi Daya"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_3.setText(_translate("MainWindow", "Run"))
from QCustomButton import QCutomButton


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QStackedWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
