from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from models.Electronic import *

class ElectronicInfo(QDialog):
    def __init__(self, electronicID : int) -> None:
        super().__init__()
        self.electronicID = electronicID
        self.getDB()
        self.setupUi()

    def setupUi(self):
        self.resize(397, 400)
        self.setObjectName("Dialog")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(150, 400))
        self.setMaximumSize(QtCore.QSize(397, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setContentsMargins(-1, 50, -1, 50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.frame = QtWidgets.QFrame(self)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(50, -1, 100, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_11 = QtWidgets.QWidget(self.frame)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 72))
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget_11)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget_11)
        self.label_7.setMinimumSize(QtCore.QSize(0, 10))
        self.label_7.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.widget_11, 0, QtCore.Qt.AlignTop)
        self.widget_12 = QtWidgets.QWidget(self.frame)
        self.widget_12.setMinimumSize(QtCore.QSize(0, 72))
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.widget_12)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget_12)
        self.label_9.setMinimumSize(QtCore.QSize(0, 10))
        self.label_9.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.widget_12, 0, QtCore.Qt.AlignTop)
        self.widget_13 = QtWidgets.QWidget(self.frame)
        self.widget_13.setMinimumSize(QtCore.QSize(0, 72))
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.widget_13)
        self.label_10.setMinimumSize(QtCore.QSize(0, 30))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget_13)
        self.label_11.setMinimumSize(QtCore.QSize(0, 10))
        self.label_11.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.widget_13, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Detail Perangkat Listrik"))
        self.label.setText(_translate("Dialog", self.electronic.getName()))
        self.label_6.setText(_translate("Dialog", "Daya"))
        self.label_7.setText(_translate("Dialog", f"{self.electronic.getWatt()} Watt"))
        self.label_8.setText(_translate("Dialog", "Voltase"))
        self.label_9.setText(_translate("Dialog", f"{self.electronic.getVoltase()} Volt"))
        self.label_10.setText(_translate("Dialog", "Waktu Penggunaan"))
        self.label_11.setText(_translate("Dialog", f"{self.electronic.getWaktu()} Jam"))

    def getDB(self):
        el = Electronic.getElectronicById(self.electronicID)
        self.electronic = el


